package com.mapoh.ppg.entity;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import javax.persistence.Table;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

/**
 * @author mabohv
 * @date 2025/1/8 19:35
 */
@Entity
@Table(name = "contracts")
public class Contract {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "contract_id", nullable = false)
    private Long contractId;

    @Column(name = "user_id", nullable = false)
    private Long userId;

    @Column(name = "merchant_id", nullable = false)
    private Long merchantId;

    @Column(name = "template_id", nullable = false)
    private Integer templateId;

    @Column(name = "contract_code", nullable = false, unique = true)
    private Long contractCode;

    @Column(name = "unit_amount", nullable = false, precision = 10, scale = 2)
    private BigDecimal unitAmount;

    @Column(name = "total_units", nullable = false)
    private Integer totalUnits;

    @Column(name = "total_amount", precision = 10, scale = 2)
    private BigDecimal totalAmount;

    @Column(name = "activation_method", nullable = false)
    @Enumerated(EnumType.STRING)
    private ActivationMethod activationMethod;

    @Column(name = "activation_date")
    private LocalDate activationDate;

    @Column(name = "latest_activation_date")
    private LocalDate latestActivationDate;

    @Column(name = "validity_period", nullable = false)
    private Integer validityPeriod;

    @Column(name = "validity_unit", nullable = false)
    @Enumerated(EnumType.STRING)
    private ValidityUnit validityUnit;

    @Column(name = "refundable")
    private Boolean refundable;

    @Column(name = "refund_fee", precision = 10, scale = 2)
    private BigDecimal refundFee;

    @Column(name = "qr_code", length = 255)
    private String qrCode;

    @Column(name = "location_info", length = 255)
    private String locationInfo;

    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @Column(name = "status")
    @Enumerated(EnumType.STRING)
    private ContractStatus status;

    // Enums for activationMethod, validityUnit, and status
    public enum ActivationMethod {
        首次消费生效, 具体日期, 最迟生效日期
    }

    public enum ValidityUnit {
        周, 月, 年
    }

    public enum ContractStatus {
        待签订, 执行中, 已完成, 已取消
    }

    // Getters and Setters (can be generated by IDE or Lombok)
    // ...

}