server:
  port: 9000
  host:
spring:
  application:
    name: ppg-gateway
  profiles:
    active: default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

zuul:
  prefix: /mapoh
  routes:
    # 用户微服务路径
    user:
      path: /ppg-user/**
      serviceId: eureka-client-ppg-user
      strip-prefix: false

    # 商家微服务路径
    merchant:
      path: /ppg-merchant/**
      service-id: eureka-client-ppg-merchant
      strip-prefix: false

    # 合同微服务路径
#    contract:
#      path: /ppg-contract/**
#      service-id: eureka-client-ppg-contract
#      strip-prefix: false
    # 合同微服务路径
    distribution:
      path: /ppg-contract/distribution/**
      service-id: eureka-client-contract-distribution
      strip-prefix: false

    template:
      path: /ppg-contract/template/**
      service-id: eureka-client-contract-template
      strip-prefix: false

    # 支付微服务
    payment:
      path: /ppg-payment/**
      service-id: eureka-client-ppg-payment
      strip-prefix: false


  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000

ribbon:
  ConnectTimeout: 15000
  ReadTimeout: 15000

custom:
  server-hosts:
    ppg-user: http://localhost:7001

# feign 相关的配置
feign:
  hystrix:
    enabled: true   # Hystrix 默认是关闭的
  client:
    config:
      default:  # 全局的
        connectTimeout: 2000  # 默认的连接超时时间是 10s
        readTimeout: 5000
      eureka-client-coupon-template:  # 单独服务的配置
        connectTimeout: 3000  # 默认的连接超时时间是 10s
        readTimeout: 5000



logging:
  level:
    com.mapoh.ppg: debug
