server:
  port: 9000
  host:
spring:
  application:
    name: ppg-gateway
  profiles:
    active: default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

zuul:
  prefix: /mapoh
  routes:
    # 用户微服务路径
    user:
      path: /ppg-user/**
      serviceId: eureka-client-ppg-user
      strip-prefix: false
    # 商家微服务路径
    merchant:
      path: /ppg-merchant/**
      service-id: eureka-client-ppg-merchant
      strip-prefix: false
    # 合同微服务
    # 商家微服务路径
    contract:
      path: /ppg-merchant/**
      service-id: eureka-client-ppg-merchant
      strip-prefix: false
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000

ribbon:
  ConnectTimeout: 15000
  ReadTimeout: 15000

custom:
  server-hosts:
    ppg-user: http://localhost:7001


logging:
  level:
    com.mapoh.ppg: debug
