server:
  port: 4001
  servlet:
    context-path: /ppg-payment

spring:
  application:
    name: eureka-client-contract-payment
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    # 数据源
    url: jdbc:mysql://127.0.0.1:3306/mapoh_ppg_data?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: Mabohv123
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 连接池
    hikari:
      maximum-pool-size: 8
      minimum-idle: 4
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 45000
      auto-commit: true
      pool-name: mapohppgHikariCP
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    # password:
    # 连接超时时间
    timeout: 10000
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 3
      acks: all
      properties:
        linger.ms: 5
        enable.idempotence: true # 开启幂等性，避免重复发送
      value-serializer: com.mapoh.ppg.serializer.ContractScheduledRequestSerializer
      transaction-id-prefix: payment_txn
    consumer:
      group-id: contract-group
      auto-offset-reset: earliest
#      防止重复消费
      enable-auto-commit: false
      value-deserializer: com.mapoh.ppg.serializer.ContractScheduledRequestDeserializer
#   开启 ribbon 重试机制, 即获取服务失败是否从另外一个节点重试
  cloud:
    loadbalancer:
      retry:
        enabled: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

logging:
  level:
    com.mapoh.ppg: debug


# feign 相关的配置
feign:
  hystrix:
    enabled: true   # Hystrix 默认是关闭的
  client:
    config:
      default:  # 全局的
        connectTimeout: 2000  # 默认的连接超时时间是 10s
        readTimeout: 5000
      eureka-client-coupon-template:  # 单独服务的配置
        connectTimeout: 3000  # 默认的连接超时时间是 10s
        readTimeout: 5000

xxl:
  job:
    admin:
      addresses: http://localhost:8160/xxl-job-admin  # XXL-JOB 调度中心地址
    executor:
      appname: my-job-executor
      ip:  # 可以留空，自动获取
      port: 9999  # 执行器端口
      logpath: /Users/bachmar/Desktop/xxl-job-2.5.0/xxl-job-admin/src/main/resources  # 日志路径
      logretentiondays: 30  # 日志保存天数
    accessToken: default_token  # 调度中心 Token（如果配置了）